# Generated by Django 5.1.2 on 2024-10-16 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VeloCare", "0002_rename_date_invoice_issue_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="service",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="VeloCare.service"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="make",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.IntegerField(),
        ),
    ]
