# Generated by Django 5.1.2 on 2024-10-17 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "VeloCare",
            "0003_alter_invoice_invoice_number_alter_invoice_service_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=datetime.date(2024, 11, 1)),
        ),
    ]
